### PR TITLE
This is cxx extension

### PR DESCRIPTION
**Pull request by remicollet**
Fix `PHP_NEW_EXTENSION` to use C++ linker, so there is no need to add` libstdc++` which is present by default with cxx command.

### CODE REVIEW

**Comment by eeliu** [comment]
@remicollet  Can you resolve this conflicts ?

**Comment by remicollet** [comment]
Rebased

**Comment by remicollet** [comment]
Notice: without this change, the build will be broken on RHEL and clones when using alternative GCC versions (gcc-toolset) which may need additional static libraries only added when invoked as cxx (so libstdc++ is not enough)

**Review by eeliu — APPROVED** [review]
LGTM

**Pull request merged**
